import {PostsRepository} from "./postsRepository";
import {PostsQueryRepository} from "./postQueryRepository";
import {PostService} from "./postService";
import {BlogsRepository} from "../blogFeature/blogsRepository";
import {PostsController} from "./postsController";
import {BlogsQueryRepository} from "../blogFeature/blogsQueryRepository";
import {CommentsRepository} from "../commentsFeature/commentsRepository";
import {CommentsService} from "../commentsFeature/commentsService";
import {CommentsQueryRepository} from "../commentsFeature/commentsQueryRepository";
import {UsersRepository} from "../usersFeature/usersRepository";
import {JWTService} from "../authFeature/JWTService";
import {RefreshTokenRepository} from "../authFeature/refreshTokenRepository";

const postsRepository = new PostsRepository();
const postsQueryRepository = new PostsQueryRepository();
const blogsRepository = new BlogsRepository();
const blogsQueryRepository = new BlogsQueryRepository();
const postService = new PostService(postsRepository, blogsRepository);
const commentsRepository = new CommentsRepository();
const usersRepository = new UsersRepository();
const refreshTokenRepository = new RefreshTokenRepository();
const commentsQueryRepository = new CommentsQueryRepository();
const commentsService = new CommentsService(commentsRepository, usersRepository);
const jwtService = new JWTService(refreshTokenRepository);
export const postsController = new PostsController(postService, blogsQueryRepository, postsQueryRepository, commentsService, commentsQueryRepository, jwtService);
